generate the test job when need

diff --git a/.gitlab/scripts.yml b/.gitlab/scripts.yml
--- a/.gitlab/scripts.yml
+++ b/.gitlab/scripts.yml
@@ -155,40 +155,35 @@
     - popd
   cache: []
 
+
 .unified_build_template:
   stage: build
   before_script:
     - !reference [.before_script_template, before_script]
-    # - !reference [.horeka_test_template, before_script]
     - if [ -z "${USE_NAME}" ]; then exit 111; fi
-    - if [ -z "${TEST_SLURM_PARTITION}" ]; then exit 222; fi
-    - if [[ ! "${TEST_SLURM_GRES}" =~ "^gpu*"  ]]; then export NVIDIA_VISIBLE_DEVICES=void; fi
-  variables: !reference [.horeka_test_template, variables]
+    - if [ -z "${TEST_SLURM_GRES}" ]; then exit 222; fi
   script:
-    - echo "RUNNER TAG ${CI_RUNNER_TAGS}"
-    - if [ "0" == "0" ]; then
-    - export CUDA_ARCH=61
-    - echo "run normal"
-    - !reference [.build_and_test_template, script]
+    - if [[ "${CI_RUNNER_TAGS}" =~ "slurm" ]]; then
+    -   !reference [.build_template, script]
+    -   if [[ "${CI_RUNNER_TAGS}" =~ "horeka" ]]; then export RUNNER_TAG=horeka; fi
+    -   export JOB_NAME="${CI_JOB_NAME#build/}"
+    -   export TEST_SLURM_GRES
+    -   export CONTAINER_NAME=${USE_NAME}
+    -   .gitlab/varsub.sh .gitlab/optional_job.yml > ${CI_JOB_NAME_SLUG}.job.yml
     - else
-    - echo "run slurm"
-    # export the build related variables
-    - if [ -n "${BUILD_KEEP_CONTAINER}" ]; then export KEEP_CONTAINER="${BUILD_KEEP_CONTAINER}"; fi
-    - if [ -n "${BUILD_USE_SLURM}" ]; then export USE_SLURM="${BUILD_USE_SLURM}"; fi
-    - !reference [.build_template, script]
-    - if [ -n "${BUILD_KEEP_CONTAINER}" ]; then unset KEEP_CONTAINER; fi
-    - if [ -n "${BUILD_USE_SLURM}" ]; then unset USE_SLURM; fi
-    # export the test related variables
-    - if [ -n "${TEST_SLURM_PARTITION}" ]; then export SLURM_PARTITION="${TEST_SLURM_PARTITION}"; fi
-    - if [ -n "${TEST_SLURM_GRES}" ]; then export SLURM_GRES="${TEST_SLURM_GRES}"; fi
-    - if [ -n "${TEST_SLURM_TIME}" ]; then export SLURM_TIME="${TEST_SLURM_TIME}"; fi
-    - !reference [.horeka_test_template, script]
-    - if [ -n "${TEST_SLURM_PARTITION}" ]; then unset SLURM_PARTITION; fi
-    - if [ -n "${TEST_SLURM_GRES}" ]; then unset SLURM_GRES; fi
-    - if [ -n "${TEST_SLURM_TIME}" ]; then unset SLURM_TIME; fi
+    -   export CUDA_ARCH=61
+    # the runner hostname is not in /etc/hosts, which leads `gethostbyname failed`
+    # we add it manually as workaround
+    -   echo "127.0.0.1   $(hostname)" >> /etc/hosts
+    -   !reference [.build_and_test_template, script]
+    -   touch ${CI_JOB_NAME_SLUG}.job.yml
     - fi
-  dependencies: []
+    - cat ${CI_JOB_NAME_SLUG}.job.yml
+  artifacts:
+    paths:
+      - ${CI_JOB_NAME_SLUG}.job.yml
   cache: []
+
 
 .horeka_benchmark_before_script_template:
   before_script:
